# Site settings
title: "Yanez Diego Parolin"
description: "My Personal Resume Website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_firstname:               "Yanez Diego"
resume_name:                    "Parolin"
resume_title:                   "B.E Computer Science & Engineering"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "yanezdiegoparolin@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+39351-8600352"
resume_contact_address:         "Località Lucchina 3, Pozzolengo, Italy"

resume_header_contact_info:     "Località Lucchina 3, Pozzolengo, Italy • +39351-860035 • yanezdiegoparolin@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a Master's Degree Student in 'Computer Science and Engineering' with a hands-on experience thanks to some jobs in this sector carried out during the bachelor's degree. I am also president of a hackerspace, after some years as vice, and this helped me to broaden the view on the context and to improve my management skills. I am looking for an internship opportunity to be carried out simultaneously with my last university year </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_associations:    true
resume_section_projects:        true
#resume_section_skills:          true
#resume_section_recognition:     true
resume_section_links:           true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/yandieg"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/yanezdiegoparolin"
  resume_instagram_url:         "https://www.instagram.com/yanezdiegoparolin/"
  resume_website_url:           "http://yandieg.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
